CREATE EXTENSION IF NOT EXISTS pg_trgm;
--> statement-breakpoint
CREATE SCHEMA IF NOT EXISTS go_router;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS go_router.routes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  destination_template text NOT NULL,
  description text NOT NULL DEFAULT '',
  tags text[] NOT NULL DEFAULT ARRAY[]::text[],
  hit_count bigint NOT NULL DEFAULT 0,
  last_used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS go_router.route_names (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_id bigint NOT NULL REFERENCES go_router.routes(id) ON DELETE CASCADE,
  name varchar(64) NOT NULL,
  normalized_name varchar(64) NOT NULL,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS route_names_normalized_name_uidx
  ON go_router.route_names(normalized_name);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS route_names_one_primary_per_route_uidx
  ON go_router.route_names(route_id) WHERE is_primary = true;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS route_names_route_id_idx
  ON go_router.route_names(route_id);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS route_names_primary_name_route_id_idx
  ON go_router.route_names(name, route_id) WHERE is_primary = true;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS route_names_name_trgm_idx
  ON go_router.route_names USING gin(name gin_trgm_ops);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS routes_created_at_id_idx ON go_router.routes(created_at, id);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS routes_updated_at_id_idx ON go_router.routes(updated_at, id);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS routes_hit_count_id_idx ON go_router.routes(hit_count, id);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS routes_last_used_sort_id_idx
  ON go_router.routes ((COALESCE(last_used_at, '-infinity'::timestamptz)), id);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS routes_description_trgm_idx
  ON go_router.routes USING gin(description gin_trgm_ops);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS routes_destination_template_trgm_idx
  ON go_router.routes USING gin(destination_template gin_trgm_ops);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS routes_tags_gin_idx ON go_router.routes USING gin(tags);
